----------------- CREACIÓN DE USUARIO ----------------------------------- 

-- Conectarse como administrador
CONNECT sys/admin AS SYSDBA;

-- Crear usuario C##corp
CREATE USER C##corp IDENTIFIED BY "corp2025";

-- Asignar cuota ilimitada en el tablespace USERS
ALTER USER C##corp QUOTA UNLIMITED ON USERS;

-- Otorgar permisos básicos de conexión
GRANT CREATE SESSION TO C##corp;

-- Otorgar roles comunes
GRANT CONNECT, RESOURCE TO C##corp;

-- Permisos para crear objetos
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, 
      CREATE SEQUENCE, CREATE TRIGGER TO C##corp;

-- Otros permisos según necesidad
GRANT SELECT ANY TABLE TO C##corp;
GRANT INSERT ANY TABLE TO C##corp;
GRANT UPDATE ANY TABLE TO C##corp;
GRANT DELETE ANY TABLE TO C##corp;


-------- DENTRO DE TEMPOALIMENTOCORP ----------------------

-- =============================================
-- ORACLE DATABASE SCRIPTS
-- =============================================

-- Tabla VENTAS
CREATE TABLE VENTAS (
    CATEGORIA VARCHAR2(100) NOT NULL,
    TIPOCLIENTE VARCHAR2(100),
    CODSUCURSAL VARCHAR2(100),
    REGION VARCHAR2(100),
    PRECIOUNITARIO NUMBER(10,2) NOT NULL,
    NUMEROCLIENTE VARCHAR2(100) NOT NULL,
    NOMBREVENDEDOR VARCHAR2(200),
    NOMBRESUCURSAL VARCHAR2(200),
    NOMBREPRODUCTO VARCHAR2(300) NOT NULL,
    NOMBRECLIENTE VARCHAR2(300) NOT NULL,
    MARCAPRODUCTO VARCHAR2(200) NOT NULL,
    FECHA DATE NOT NULL,
    DIRECCIONSUCURSAL VARCHAR2(300) NOT NULL,
    DIRECCIONCLIENTE VARCHAR2(300) NOT NULL,
    DEPARTAMENTO VARCHAR2(300),
    CODVENDEDOR VARCHAR2(100) NOT NULL,
    CODPRODUCTO VARCHAR2(100) NOT NULL,
    CODIGOCLIENTE VARCHAR2(100) NOT NULL,
    UNIDADES NUMBER(38,0) NOT NULL,
    VACACIONISTA VARCHAR2(200)
);

-- Tabla COMPRAS
CREATE TABLE COMPRAS (
    FECHA DATE NOT NULL,
    CODEPROVEEDOR VARCHAR2(100) NOT NULL,
    NOMBREPROVEEDOR VARCHAR2(300) NOT NULL,
    DIRECCIONPROVEEDOR VARCHAR2(300),
    NUMEROPROVEEDOR VARCHAR2(100),
    WEBPROVEEDOR VARCHAR2(100),
    CODPRODUCTO VARCHAR2(100),
    NOMBREPRODUCTO VARCHAR2(300) NOT NULL,
    MARCAPRODUCTO VARCHAR2(200),
    CATEGORIA VARCHAR2(100),
    CODSUCURSAL VARCHAR2(100),
    NOMBRESUCURSAL VARCHAR2(200),
    DIRECCIONSUCURSAL VARCHAR2(300),
    REGION VARCHAR2(100),
    DEPARTAMENTO VARCHAR2(100),
    UNIDADES NUMBER(38,0) NOT NULL,
    COSTOU NUMBER(10,2) NOT NULL
);
