-- Tabla VENTAS
CREATE TABLE VENTAS (
    CATEGORIA VARCHAR(100) NOT NULL,
    TIPOCLIENTE VARCHAR(100) NULL,
    CODSUCURSAL VARCHAR(100) NULL,
    REGION VARCHAR(100) NULL,
    PRECIOUNITARIO DECIMAL(10,2) NOT NULL,
    NUMEROCLIENTE VARCHAR(100) NOT NULL,
    NOMBREVENDEDOR VARCHAR(200) NULL,
    NOMBRESUCURSAL VARCHAR(200) NULL,
    NOMBREPRODUCTO VARCHAR(300) NOT NULL,
    NOMBRECLIENTE VARCHAR(300) NOT NULL,
    MARCAPRODUCTO VARCHAR(200) NOT NULL,
    FECHA DATE NOT NULL,
    DIRECCIONSUCURSAL VARCHAR(300) NOT NULL,
    DIRECCIONCLIENTE VARCHAR(300) NOT NULL,
    DEPARTAMENTO VARCHAR(300) NULL,
    CODVENDEDOR VARCHAR(100) NOT NULL,
    CODPRODUCTO VARCHAR(100) NOT NULL,
    CODIGOCLIENTE VARCHAR(100) NOT NULL,
    UNIDADES BIGINT NOT NULL,
    VACACIONISTA VARCHAR(200) NULL
);

-- Tabla COMPRAS
CREATE TABLE COMPRAS (
    FECHA DATE NOT NULL,
    CODEPROVEEDOR VARCHAR(100) NOT NULL,
    NOMBREPROVEEDOR VARCHAR(300) NOT NULL,
    DIRECCIONPROVEEDOR VARCHAR(300) NULL,
    NUMEROPROVEEDOR VARCHAR(100) NULL,
    WEBPROVEEDOR VARCHAR(100) NULL,
    CODPRODUCTO VARCHAR(100) NULL,
    NOMBREPRODUCTO VARCHAR(300) NOT NULL,
    MARCAPRODUCTO VARCHAR(200) NULL,
    CATEGORIA VARCHAR(100) NULL,
    CODSUCURSAL VARCHAR(100) NULL,
    NOMBRESUCURSAL VARCHAR(200) NULL,
    DIRECCIONSUCURSAL VARCHAR(300) NULL,
    REGION VARCHAR(100) NULL,
    DEPARTAMENTO VARCHAR(100) NULL,
    UNIDADES BIGINT NOT NULL,
    COSTOU DECIMAL(10,2) NOT NULL
);
